from fastapi import FastAPI, status, HTTPException, Response
from backend.api.schemas.item import ItemCreate, ItemUpdate, ItemResponse
from datetime import datetime, timezone
from itertools import count

# TODO: separate class 'DatabaseConnector' with methods for CRUD and autogenerated increment via 'count'
id_generator = count(start=0)

items = {}

app = FastAPI(title="Latera")

@app.get("/items", status_code=status.HTTP_200_OK, response_model=list[ItemResponse])
def get_items():
    return [ItemResponse(item_id=k, **v) for k, v in items.items()]

@app.get("/items/{item_id}", status_code=status.HTTP_200_OK, response_model=ItemResponse)
def get_item(item_id: int):
    if item_id not in items:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="no item with such id"
        )
    
    return ItemResponse(item_id=item_id, **items[item_id])

@app.post("/items", status_code=status.HTTP_201_CREATED, response_model=ItemResponse)
def create_item(item: ItemCreate):
    if not item.content or item.content.isspace():
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail="content field must not be empty"
        )

    new_id = next(id_generator)

    items[new_id] = {
        "title": item.title,
        "content": item.content,
        "created_at": datetime.now(timezone.utc),
        "modified_at": None
    }

    new_item = ItemResponse(item_id=new_id, **items[new_id])

    return new_item

@app.patch("/items/{item_id}", status_code=status.HTTP_200_OK, response_model=ItemResponse)
def update_item(item_id: int, new_item: ItemUpdate):
    if item_id not in items:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="no item with such id"
        )

    update_data = new_item.model_dump(exclude_unset=True)
    old_item = items[item_id]
    modified = False

    if not update_data:
        return ItemResponse(item_id=item_id, **old_item)

    if "content" in update_data and old_item["content"] != new_item.content:
        if (new_item.content is None) or (
            new_item.content is not None and (not new_item.content or new_item.content.isspace())
        ):
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
                detail="content field must not be empty"
            )
        
        old_item["content"] = new_item.content
        modified = True

    if "title" in update_data and old_item["title"] != new_item.title:
        old_item["title"] = new_item.title
        modified = True

    if modified:    
        old_item["modified_at"] = datetime.now(timezone.utc)
    
    return ItemResponse(item_id=item_id, **old_item)

@app.delete("/items/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_item(item_id: int):
    if item_id not in items:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="no item with such id"
        )

    items.pop(item_id)

    return Response(status_code=status.HTTP_204_NO_CONTENT)
